os:
  - linux
services:
  - docker
language: node_js
node_js:
  - "9.8.0"
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
sudo: false
cache:
  directories:
    - node_modules
before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g ionic
install:
  - cd `dirname $0` && r=`pwd` && echo $r
  - git clone https://github.com/ionic-team/starters.git
  - cd $r/starters/ionic-angular/community/oktadeveloper/jhipster && npm pull origin master
  - cd $r/starters && npm run starters:build -- ionic-angular/community/oktadeveloper/jhipster
  - cd $r/starters/build/ionic-angular-community-oktadeveloper-jhipster
script:
  - npm test
  - ionic-serve &
  - npm run e2e
notifications:
  webhooks:
    on_success: always
    on_failure: always
    on_start: false